string tree_file
bool debug
bool auto_restart
uint32 publisher_port
uint32 server_port
string[] bb_init_files
string deployed_capability
uint32 max_load_timeout_ms
---
uint32 tree_uid
bool started
bool instantiated